Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include  # include is needed for including folders as addresses. ( or paths )

urlpatterns = [
    path('admin/', admin.site.urls),
	path('main/', include("main.urls")), # i need to put this here so that every application that is a part of this project can reach main's url file.
]

main/urls.py
from django.urls import path
from . import views

# handler404 = 'views.notfound'
# handler500 = 'views.oopsiewoopsie'

urlpatterns = [
	path('', views.index, name="index"),                                # localhost:8000/main/
	path('base', views.base, name="base"),								# You are not supposed to be here.
	path('auth/SignIn', views.SignIn, name="SignIn"),                   # localhost:8000/main/auth/SignIn
	path('auth/SignIn2', views.SignIn2, name="SignIn2"),				# this is the google sign in page.
	path('auth/SignOut', views.SignOut, name="SignOut"),                # localhost:8000/main/auth/SignOut
	path('auth/register', views.register, name='register'),             # localhost:8000/main/auth/register
	path('user/profile_edit', views.profile_edit, name='profile_edit'), # localhost:8000/main/user/profile_edit
	path('user/<str:username>', views.profile, name='profile'),         # localhost:8000/main/user/(username) Note that if you change the length of this url you will need to edit the profile view accordingly.
	path('auth/recovery', views.recovery, name='recovery'),				# localhost:8000/main/auth/recovery
	path('auth/recovered/<str:value>', views.recovered, name='recovered'),
	path('dummy', views.dummy, name='dummy'),							# localhost:8000/main/dummy   This is a test page for comments.
	path('test', views.test, name='test'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class UserDescription(models.Model): 		# This is the model for the descriptions of users.
	description = models.TextField()
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	
	
	def __str__(self):
		return self.description
		
class Post(models.Model):
	content = models.TextField()
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.content
	

	
	
"""
class User(models.Model):   # models.Model is the database that the application uses, and is defined in the settings.py file.
	# An ID field is put in here by default, so i do not need to add one.
	username = models.CharField(max_length=32)       # Username of user.
	email = models.CharField(max_length=64, default="kek@kek")         # i do not want multiple users to create accounts on one email, as that makes it easier for bots register accounts. and that is BAD! (atleast i assume that is why this matters)
	password = models.CharField(max_length=20, default="no")					   # no real restrictions needed for a password, other than not leaving it blank
	
	def __str__(self): # returns question_text as a string instead of the data.
		return self.username
		
	def username_exists(self):   # returns a boolean based on wether or not the publish date is less than a day old.
		return self.username
		
	def email_exists(self):
		return self.email
		
	def password_exists(self):
		return self.password
"""

main/forms.py
from django import forms

class UsernameForm(forms.Form):   # gets rendered as 2 fields that contain a username and password.
	username = forms.CharField(label='Username goes here', max_length=100)
	password = forms.CharField(label='Password goes here', max_length=100)
	

	
class RegisterForm(forms.Form):
	username = forms.CharField(label='Username goes here', max_length=32)
	password = forms.CharField(label='Password goes here', max_length=32)
	password2 = forms.CharField(label='Re-enter your password', max_length=32)
	email = forms.EmailField(label='Enter your email here')
	
class SearchForm(forms.Form):
	search = forms.CharField(label='search', max_length=32)
	
	
class EditForm(forms.Form):
	edit = forms.CharField(max_length=140)
	
class PostForm(forms.Form):
	post = forms.CharField(max_length=300)
	
class RecoveryForm(forms.Form):
	email = forms.EmailField(label='Email:')
	
class RecoveryForm2(forms.Form):
	password1 = forms.CharField(label='Enter your new password.', max_length=99)
	password2 = forms.CharField(label='Again!', max_length=99)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UsernameForm, RegisterForm, SearchForm, EditForm, PostForm, RecoveryForm, RecoveryForm2
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, UserManager
from django.core import validators
from .models import UserDescription, Post
from django.urls import reverse 
from django.core.mail import send_mail
from django.utils.crypto import get_random_string
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from django.shortcuts import render

keylength = 32


def test(request):
	return render(request, "main/test.html")

def index(request):  # request turns to localhost:8000.
	searchform = SearchForm()
	if request.user.is_authenticated:
		return render(request, 'main/index.html', {'searchform': searchform, 'login': True})
	return render(request, 'main/index.html', {'searchform': searchform})

def base(request):
	return render(request, 'main/base.html')

def SignIn(request):
	if request.user.is_authenticated:				   # lets me test for sure if user is logged in.
		return redirect('/main/')
	form = UsernameForm()
	if request.method == 'POST':                       # If the page is accessed by means of POST, try to log in the user.
		form = UsernameForm(request.POST)
		if form.is_valid():
			usern = form.cleaned_data.get('username')			   # The only way to access this page is via trying to log in anyway, so it should be fine.
			passw = form.cleaned_data.get('password')
			user = authenticate(request, username=usern, password=passw) # checks the database for the current information.
			if user is not None:						   # If the user does in fact exist log them in.
				login(request, user)
				return redirect(reverse('index')) # If the user is valid, log them in and redirect them to the index page.
			return render(request, 'main/auth/SignIn.html', {'userform': form, 'invalid': True})	
	return render(request, 'main/auth/SignIn.html', {'userform': form})  # if the user is not accessing this page via post then show them the SignIn page.
	
	
def SignIn2(request):
	return render(request, 'main/auth/SignIn2.html')

def SignOut(request):
	logout(request)
	return redirect('/main/')
	
	
def register(request):
	if request.user.is_authenticated:
		logout(request)
	if request.method == "POST":
		form = RegisterForm(request.POST) # request.post is all of the information POSTed from the page, which is the username email passwords etc. in this case.
										  # i also specify that only information from the RegisterForm be read here, because not doing to could potentially cause mishaps later on in development.
		if form.is_valid():               # cleans the data from the form (eg removes the text and saves it as variables)
			usernam = form.cleaned_data.get('username')
			mailE = form.cleaned_data.get('email')
			pass1 = form.cleaned_data.get('password')
			pass2 = form.cleaned_data.get('password2')
			checkname = User.objects.filter(username=usernam)
			checkemail = User.objects.filter(email=mailE)
			if pass1 == pass2:
				if usernam == "profile_edit":
					return render(request, 'main/auth/register.html', {'registerform': form, 'invalid': True})
				if checkname.exists():
					return render(request, 'main/auth/register.html', {'registerform': form, 'taken': True})
				if checkemail.exists():
					return render(request, 'main/auth/register.html', {'registerform': form, 'etaken': True})
				sav = User.objects.create_user(username=usernam, email=mailE, password=pass1)
				sav.save()
				desc = UserDescription.objects.create(owner=User.objects.get(username=usernam), description='')
				desc.save()
				return render(request, 'main/auth/register.html', {'registerform': form, 'registered': True})
	form = RegisterForm()
	return render(request, 'main/auth/register.html', {'registerform': form})
	
def profile(request, username):
	if request.user.is_authenticated:
		boi = request.user.username
		memo = request.path
		mem2 = memo[11:]
		userdescription = UserDescription.objects.get(owner__username=mem2).description
		#print(request.path)
		memo = request.path
		#print(memo[11:])
		return render(request, 'main/user/profile.html', {'userdescription': userdescription , 'username' : username}) # request.user.username should be the profiles owner, not the guy who is logged in, but this is for testing.
	return redirect(reverse('index')) # redirect originates from where you are, not the base directory! a reverse is needed!
	
	
def profile_edit(request):
	if request.user.is_authenticated:
		if request.method == "POST":
			form = EditForm(request.POST)
			
			if form.is_valid():
				info = form.cleaned_data.get('edit')
				sav = UserDescription.objects.get(owner__username=request.user.username)
				sav.description = info 
				sav.save()
				return redirect(reverse('profile', args=[request.user.username]))
		form = EditForm()
		return render(request, 'main/user/profile_edit.html', {'editform' : form, 'currentdescription': UserDescription.objects.get(owner__username=request.user.username).description})
	return redirect(request, 'main/')
	
	
def dummy(request):
	if request.user.is_authenticated:
		request.session.cycle_key()
		if request.method == "POST":
			form = PostForm(request.POST)
			
			if 'delete' in request.POST:
				deli = request.POST.get('oiy')
				kekp = request.POST.get('oin')
				Post.objects.filter(author__username=request.user.username,
									content=deli, pk=kekp).delete()
			if form.is_valid():
				info = form.cleaned_data.get('post')
				kek = Post.objects.create(author=User.objects.get
										(username=request.user.username),
										content=info)
				kek.save()
		
		commentlist = Post.objects.all().order_by("-pk")
		paginator = Paginator(commentlist,10) # display 10 comments per page.
		form = PostForm()
		page = request.GET.get('page')
		comments = paginator.get_page(page)
		return render(request, 'main/dummy.html', {'postform' : form, 'posts' : comments})
	return redirect(reverse('index'))
	
	
def recovery(request):
	if request.user.is_authenticated:
		return redirect(reverse('index'))
	request.session['value'] = get_random_string(length=keylength)

	form = RecoveryForm()
	if request.method == "POST":
		form = RecoveryForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data.get('email')
			try:
				usr = str(User.objects.get(email=email))
				request.session['user'] = usr
			except User.DoesNotExist:
				return render(request, 'main/auth/recovery.html' , {'recoveryform' : form, 'nosend' : True})
			request.session['email'] = ''
			if User.objects.filter(email=email).exists():
				key = request.session.get('value')
				template = render_to_string('main/email/Email_template.html', {'link': key})
				plain = render_to_string('main/email/Email_template.txt', {'link': key})
				send_mail('Password Recovery', plain, 'TrymPortfolio@outlook.com', [email], html_message = template)
				return render(request, 'main/auth/recovery.html', {'recoveryform' : form, 'sent': True})
	return render(request, 'main/auth/recovery.html', {'recoveryform' : form})
	

	
def recovered(request, value):				
	if request.session.get('value') == request.path[-keylength:]:
		if request.method == 'POST':
			form = RecoveryForm2(request.POST)
			if form.is_valid():
				password1 = form.cleaned_data.get('password1')
				password2 = form.cleaned_data.get('password2')
				if password1 == password2:
					user = User.objects.get(username=request.session.get('user'))
					user.password = password1
					user.save()
					request.session.flush()
					return render(request, 'main/auth/recovered.html', {'form': form, 'change' : True})
				else:
					return render(request, 'main/auth/recovered.html', {'form': form, 'error' : True})
		else:
			form = RecoveryForm2()
			return render(request, 'main/auth/recovered.html', {'form': form })
	else:
		print(request.path[-keylength:])
		print(request.session.get('value'))
		return redirect(reverse('recovery'))
		
		
		
def notfound(request):
	return render(request, 'main/error/404.html')
	
def oopsiewoopsie(request):
	return render(request, 'main/error/500.html')

templates/main/_post.html
<div class="postbox">
	<table width="100%">
		<tbody class="top_row">
			<tr class="top_row">
				<td class="post_td">
					<a href="{% url 'profile' username=post.author.username %}">  <!-- we create a link to the users profile and then we set the username variable to be equal to post.author.username -->
						{{ post.author.username }}                                   <!-- the translated username is a link to the profile -->	
					</a>
				</td>
				<td class="post_td">
					{% if post.author.username == request.user.username %}
						<form action="{% url 'dummy' %}" method="post" class="button_del_form">
							{% csrf_token %}
							<input hidden class="form-control" name="oin"   value="{{ post.pk }}">
							<input hidden class="form-control" name="oiy"   value='{{ post.content }}'>
							<input type="submit" id="{{ post.pk }}" name="delete" value="X" class="button_del">
						</form>
					{% endif %}
				</td>
			</tr>
			<tr>
				<td class="post_td">
					{{ post.content }}
				</td>
			</tr>
		</tbody>
	</table>
</div>

templates/main/base.html
<!DOCTYPE html>
<html>
{% load static %} <!-- loads the content of the static folder. -->
 <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
 <link rel="stylesheet" type="text/css" href="{% static 'post.css' %}">
<head>
	{% block title %} <!-- this block displays (title variable here) - Portfolio if there is a title variable set when the html page containing this block is called. -->
	{% endblock %}
	{% block navbar %}
		<div id="navbar" class="row">
			<ul>
				<li><a href="{% url 'index' %}" class="navbutton">Index</a></li>
			</ul>
			<ul id="navbarright">
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'SignOut' %}" class="navbutton">Sign Out</a></li>
				<li><a href="{% url 'profile' request.user.username %}" class="navbutton">Profile</a></li>
				<li><a href="{% url 'dummy' %}" class="navbutton">Dummy</a></li>
				{% else %}
				<li><a href="{% url 'SignIn' %}" class="navbutton">Sign In</a></li>
				<li><a href="{% url 'SignIn2' %}" class="navbutton">Google Sign in</a></li>
				{% endif %}
			</ul>
		</div>
	{% endblock %}
</head>
<body>
<div class="content">
	<div class="row">
		<div class="column left">
			{% block left %}
			<p></p>
			{% endblock %}
		</div>
		<div class="column center">
			{% block content %}
			{% endblock %}
		</div>
		<div class="column right">
			{% block right %}
			<p></p>
			{% endblock %}
		</div>
	</div>
</div>
	<footer class="footer"><p class="foot">Memes</p></footer>
</body>
</html>

templates/main/dummy.html
{% extends "main/base.html" %}
{% block title %}
	<h1 class="main_head">Post your comments below!</h1>
{% endblock %}
{% block content %}
	<p>(This page is only temporary as there are no actual projects to show off yet.)</p>
	<form method="post" id="EditForm">
		{% csrf_token %}
		<table class="table formtable">
			<tr>
				<td><textarea id="id_post" name="post" placeholder="Comment..." class="boxinput_post"></textarea></td>
			</tr>
			<tr>
				<td><input type="submit" value="Comment"></td>
			</tr>
		</table>
	</form>
	{% for post in posts %}
		{% include 'main/_post.html' %}
	{% endfor %}
	
	<div class="pagination">
		<span class="step-links">
			{% if posts.has_previous %}
				<a href="?page=1">&laquo; first</a>
				<a href="?page={{ posts.previous_page_number }}">previous</a>
			{% endif %}
			
			<span class="current">
				page {{ posts.number }} of {{ posts.paginator.num_pages }}.
			</span>
			
			{% if posts.has_next %}
				<a href="?page={{ posts.next_page_number }}">next</a>
				<a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>
{% endblock %}

templates/main/index.html
{% extends "main/base.html" %}
{% block title %}
	<h1 class="main_head">PORTFOLIO</h1>
{% endblock %}
{% block content %}
	{% if login %}
		<p name="login">YOU HAVE LOGGED IN</p>
		<br>
	{% endif %}
	<p> THIS WOKRS! </p>
{% endblock %}

templates/main/test.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Create three unequal columns that floats next to each other */
.column {
  float: left;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
}

.left, .right {
  width: 25%;
}

.middle {
  width: 50%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>
<body>

<h2>Three Unequal Columns</h2>

<div class="row">
  <div class="column left" style="background-color:#aaa;">
    <h2>Column 1</h2>
    <p>Some text..</p>
  </div>
  <div class="column middle" style="background-color:#bbb;">
    <h2>Column 2</h2>
    <p>Some text..</p>
  </div>
  <div class="column right" style="background-color:#ccc;">
    <h2>Column 3</h2>
    <p>Some text..</p>
  </div>
</div>

</body>
</html>